### ISSUE TITLE
The record schemas in Kafka.

### ISSUE THREAD

**Issue by XxZhang2017** [bkatwal/kafka-solr-sink-connector#1]
Probably we need some exception handler if record schema doesn't meet the requirement.

**Comment by bkatwal** [comment]
Thanks for pointing that out. I am expecting plain json data which is parsed to  schema less record. So, added a condition and will log an error if condition does not match.
added change in SolrSinkTask. Hope that helps.

**Comment by bkatwal** [comment]
closing this issue.
