### ISSUE TITLE
Solr Sink Connector Showing the document in Id and version format only

### ISSUE THREAD

**Issue by nik09541** [bkatwal/kafka-solr-sink-connector#3]
Hi @bkatwal 
I had implemented a use case for solr sink where data is being pulled from oracle source connector and solr is being used as sink connector. Intermediary I have an application which appends the Json from source with another Json  thaty is being made from Java code  and consolidated json is sent to the output topic which is mentioned in solr.properties (checked that Json formed is valid one). The problem being faced is that documents get displayed in id and version format only. Is there anything that we have to map the schema of whole json also. To bring to our notice I started solr in schemaless mode . Adding the screenshot of the solr admin page.
![capture](https://user-images.githubusercontent.com/44663724/50465747-4276db80-09bf-11e9-8c90-37ca0c39f7eb.JPG)

Please help if I am missing anything.

**Comment by bkatwal** [comment]
Hi @nik09541,

Could you please send the json that you pulling from oracle source connector? 
Please confirm if you are using _default schema for your collection?

**Comment by nik09541** [comment]
Hi @bkatwal
Yes we are using the default schema.The json being sent to solr is nested one in the following format:

{
	"otherDetails": {
		"initialReceiverReference": null,
		"swapPremium": null,
		"interFundingFundCodeDestination": null,
		"couponPaymentAmount": null,
		"unitPrice": null,
		"principalExchangeDescriptions": null,
		"numberOfUnits": null,
		"principalCurrency": null,
		"switchNumber": null,
		"principal": null,
		"notionalCurrency": null,
		"interestAtMaturity": null,
		"interest": null,
		"netTradeIndicator": null,
		"quantity": null,
		"yieldToMaturity": null,
		"exchangeId": 0,
		"optionType": null,
		"dividendPayoutRatio": null,
		"optionEntitlement": null,
		"settlementType": null,
		"dimSumBond": null,
		"depositoryReceipt": null,
		"equityExercise": null,
		"dividendPayoutConditions": null,
		"methodOfAdjustment": null,
		"fillIsExecutionInd": null,
		"switchType": null,
		"openUnits": null,
		"preTradeDisclosureWaiver": null,
		"fixedRate": null,
		"transactionSubType": null,
		"specialInstructions": null,
		"startDate": null,
		"previousclosesecurityprice": null,
		"exerciseStyle": null,
		"underlyerNotional": null,
		"constituentWeight": null,
		"equityEffectiveDate": null,
		"dirtyExecutedPriceCurrency": null,
		"version": null,
		"currency": null,
		"exchangeLookAlike": null,
		"strikeDeterminationRelativeDate": null,
		"dirtyExecutedPrice": null,
		"numberOfOptions": null,
		"brokerSIFlag": null,
		"inspecieFlag": null,
		"deliveryType": null,
		"paymentType": null,
		"accruedInterestCurrency": null,
		"earlyTerminationStartingDate": null,
		"orderRoutingAlgoId": 0,
		"maturityDate": null,
		"dividendPaymentCurrency": null,
		"factor": null,
		"additionalPaymentDate": null,
		"novationFlag": null,
		"exchangeCode": null,
		"transactionType": null,
		"interFundingtradeIdOpposite": null,
		"notional": null,
		"interFundingfundMnemonicDestination": null,
		"lastLiquidityIndicator": null,
		"spotPrice": null,
		"equityPremiumPaymentDate": null,
		"averageDailyTradingVolumeLimitationPercentage": null,
		"principalExchanges": null,
		"couponPaymentAccruedInterestCurrency": null,
		"comments": null,
		"cleanExecutedPrice": null,
		"accrualType": null,
		"percentageOfNotional": null,
		"averageDailyTradingVolumeLimitationPeriod": null,
		"underlyingAsset": null,
		"usdexchangerate": null,
		"couponPaymentDate": null,
		"packageId": 0,
		"relatedExchangeId": 0,
		"exchangeTradedContractNearest": null,
		"deliverydate": null,
		"cancelReason": null,
		"componentSecurityIndexAnnexFallback": null,
		"dividendPaymentAccuruedInterestCurrency": null,
		"deliveryPrice": null,
		"earlyTerminationPartyId": 0,
		"downStreamEligibility": null,
		"ipoflag": null,
		"extraordinaryEvents": null,
		"dividendPaymentAccruedInterest": null,
		"crossCCYFX": null,
		"systemOfOrigin": null,
		"underlyerNotionalCurrency": null,
		"futureValueAllocation": null,
		"multipleExchangeIndexAnnexFallback": null,
		"interestCurrency": null,
		"issuerCode": null,
		"dividendPaymentAmount": null,
		"strikePrice": null,
		"couponPaymentAccruedInterest": null,
		"couponPaymentAmountCurrency": null,
		"tradingStrategy": null,
		"interestAtMaturityCurrency": null,
		"longShortIndicator": null,
		"optionsExchangeId": 0,
		"discountRate": null,
		"affirmedIndicator": null,
		"accrualdays": null,
		"countryOfRisk": null,
		"localJurisdiction": null,
		"strikePercentage": null,
		"underlyerSpread": null,
		"pricePerOptionCurrency": null,
		"underlyerPrice": null,
		"novationRemainingParty": null,
		"blockExecutedQuantity": null,
		"initialPayerReference": null,
		"investmentDecisionMaker": null,
		"paymentAmount": null,
		"priceMultiplier": null,
		"collateral": null,
		"additionalPaymentAmount": null,
		"benchmarkFMRSecurityID": null,
		"effectiveMaturityDate": null,
		"indexfactor": null,
		"transFinerType": null,
		"nofx": null,
		"venueType": null,
		"lotSize": null,
		"postTradeDisclosureWaiver": null,
		"strikeDeterminationAdjustableDate": null,
		"premiumType": null,
		"paymentAmountCurrency": null,
		"allocationTradingStrategy": null,
		"accruedInterest": null,
		"tbaIndicator": null,
		"pricePerOption": null,
		"allocatedFraction": null,
		"dividendPaymentDate": null
	},
	"person": {
		"modifierId": 0,
		"creatorName": null,
		"modifierName": null,
		"tradingDesk": null,
		"traderId": 0,
		"creatorAlternateId": 0,
		"creatorId": 0,
		"modifierAlternateId": 0,
		"traderName": null,
		"traderInitials": null
	},
	"brokerSettlementDetails": {
		"securityAccountName": null,
		"executingBrokerBIC": null,
		"clearingBrokerShortName": null,
		"centralCounterparty": null,
		"correspondingAgentId": 0,
		"executingBrokerShortName": null,
		"clearingBrokerBIC": null,
		"securityAccountBeneficiary": null,
		"settlerAgentBicCode": null,
		"custodian": null,
		"securityAccountId": 0,
		"oasysGlobalBrokerId": 0,
		"executingBrokerName": null,
		"autoSettle": null,
		"clearingBrokerName": null,
		"pset": null,
		"depositaryParticipentId": 0,
		"executingBrokerInvest1Id": 0,
		"clearingBrokerInvest1Id": 0
	},
	"ids": {
		"transactionId": 0,
		"cancelTradeId": 0,
		"sourceTradeId": 0,
		"originalOrderId": 0,
		"tradingVenueTxnId": 0,
		"messageId": 0,
		"orderId": 0
	},
	"financials": {
		"allocation": null,
		"block": null
	},
	"fund": {
		"fmrNumber": null,
		"fundShortName": null,
		"logicalSubPortfolioId": null,
		"eomsId": 0,
		"parentFundShortName": null
	},
	"security": {
		"contractExpiration": null,
		"expirationDate": null,
		"couponRate": null,
		"maturity": null,
		"grdIvtype": null,
		"couponType": null,
		"fmrCusip": null,
		"crdSecurityType": null,
		"sedol": null,
		"paymentFrequencyPeriod": null,
		"paymentFrequencyPeriodMultiplier": null,
		"issueCountryCode": null,
		"multiplier": null,
		"currency": null,
		"dayCountFraction": null,
		"issuerPartyReference": null,
		"grdStructureType": null,
		"parValue": null,
		"issuerName": null,
		"faceAmount": null,
		"securityName": null,
		"seniority": null,
		"futureContractReference": null,
		"isin": null
	},
	"statuses": {
		"tradeStatus": null,
		"accountingStatus": null,
		"settlementStatus": null,
		"matchingStatus": null,
		"tradeRepair": null,
		"orderStatus": null
	},
	"datesAndTimeStamps": {
		"messageCreationTimeStamp": null,
		"allocationCreationDateTime": null,
		"contractualSettlementDate": null,
		"masterConfirmationDate": null,
		"placementTime": null,
		"sendAcctDateTime": null,
		"messageExpiryTimeStamp": null,
		"modifiedDate": null,
		"executionDateTime": null,
		"tradeDate": null,
		"settlementDate": null,
		"brokerVenueExecutionTime": null,
		"effectiveDate": null
	},
	"tradeCrossRefMetadata": {
		"tradeCrossRefId": 4709795,
		"spInstructions": null,
		"tradeId": 416092166,
		"accountId": 1220223,
		"fundAcronym": "FIJJG",
		"fundName": null,
		"quantity": 15438520,
		"valuationPoint": "1701",
		"effectiveDate": "2019-01-02T04:55:34.345",
		"currencyCode": "USD",
		"netSettlementAmount": 15438520,
		"tradePrice": 1546,
		"isFmrFund": "N",
		"createdBy": "null",
		"inv1Memo_": "23867081",
		"createdDate": "02-Jan-19 04:55:34.345000000",
		"instrumentId": "86562X924",
		"updatedBy": "null",
		"updatedDate": "02-Jan-19 04:55:34.345000000",
		"blockId": 0,
		"cancelRef": 0,
		"executedAmount": 270000,
		"traderName": "Cross",
		"tradingDesk": "TRADERS",
		"fmrFxCreated": null,
		"crdTradeId": "16065292JGROW1",
		"settlementCurrency": "JPY",
		"settlementDate": null,
		"reversalTradeId": "988745",
		"autoConfirm": null,
		"matchingStatus": "CONFIRM",
		"confirmationStatusId": 2,
		"wireId": null,
		"buySell": "BUY",
		"counterPartyCode": "EXANEUAL",
		"fees": 0,
		"tax": 154,
		"commission": 8.28,
		"tradeOrigin": "FIL",
		"sourceCancelId": null,
		"is_crossCcyBond": null,
		"replicatedTradeId": 254879,
		"isReplicatedTrade": null,
		"isReversed": null,
		"invEffectiveDate": null,
		"relatedFxTrade": 12563,
		"twsFxDealType": null,
		"fxExchangeRate": null,
		"custodyStatus": null
	},
	"transactionMetadata": {
		"transactionId": 1200300,
		"correlationId": null,
		"parentTransactionId": null,
		"transactionStatusId": null,
		"transactionTypeId": 28,
		"sourceSystem": "null",
		"targetSystem": "null",
		"comments": null,
		"createdBy": "null",
		"createdDate": "02-Jan-19 10:25:31.625000000",
		"updatedBy": "TWS",
		"updatedDate": "02-Jan-19 10:25:31.625000000",
		"tradeCrossRefId": null,
		"blockId": null,
		"instrumentId": null,
		"issuerId": null,
		"mqCorrelationId": "414d51204d514855425034302020202059b43a3225f13fc5",
		"versionNo": 1,
		"blockAckFlag": null,
		"financialTxnCrossRefId": null,
		"lastUpdatedUser": null
	}
}

Please help over the same as the end document getting displayed is only in form Id and version

**Comment by bkatwal** [comment]
@nik09541  You need to flatten your json, this nested json will not be indexed. Solr supports only flatten type or list of values as multi value field. The id field is generated by solr as its schemaless and you are not passing id and version is document version that is generated by solr.
You can post this document for solr admin UI itself and see result. Just go to "Documents" section in left nav, after selecting your collection and submit this document.

Process your data and flatten it, for instance, if you want to store unit_price under otherDetails field, you can create field like otherDetails.unit_price, instead of created nested fields.

**Comment by nik09541** [comment]
Hey @bkatwal  for early reply
In here our use case is designed so that we are forming this json in our code in order to process all the transaction fields in particular trade. The nested json is needed as it is. Is there anything like elastic search in Solr where it reads whole of plain nested json as it is . In elastic search sink I have tried the same  i works well but due to infra issues we dont have provision for elastic search. In case any workaround other than flattening the json. 

Thanks in Advance

**Comment by bkatwal** [comment]
@nik09541  No Search engine will provide nested document search of this kind, you need to flatten your json(can keep list of values) to search upon it. 
If you can not flatten, what I would recommend is,  you create different collection for each document otherDetails, person, financials, tradeCrossRefMetadata etc etc. 
Solr and elastic search supports childDocuments and Nested documents feature separately. But that is completely different use case. Where your array of nested documents have  same fields.
https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html
https://medium.com/@pablocastelnovo/nesting-documents-in-apache-solr-12ef44ea2901
You have to either flatten or use different collections for each field in your master document.
I am closing this issue. You can address this in forums like stackoverflow

**Comment by nik09541** [comment]
Thanks for help Bikas.

Regards
Nikhil
