### ISSUE TITLE
Getting compile time error 

### ISSUE THREAD

**Issue by ramyogi** [bkatwal/kafka-solr-sink-connector#5]
r/src/main/java/com/bkatwal/kafkaproject/utils/SolrSinkService.java

All the "log" variable ?

**Comment by bkatwal** [comment]
Where you are getting compilation error? 
What's your build command? 
Please post the failure log.

**Comment by ramyogi** [comment]
It is build properly, I just clone the project and import that in Intellij and try to build. I could see the "log" variable not resolve. Might be my environment issue.

![image](https://user-images.githubusercontent.com/1988551/64324400-3b788200-cfbe-11e9-8a99-b80186b1b683.png)

**Comment by ramyogi** [comment]
[2019-09-05 12:20:22,536] ERROR WorkerSinkTask{id=TestSolrSinkConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:558)


Can you help how to getrid of this one, If any error just ignore and proceed or push the message to another topic failed topic.
Any worker/connector plugin property will help ?

I used errors.tolerance=all but seems not working.

**Comment by bkatwal** [comment]
On your previous message. Use the Lombok plugin in IntelliJ to get rid of compile type error in Intellij.
To run the sink connector.
Can you follow the steps in confluent:
https://www.confluent.io/hub/bkatwal/bkatwal-kafka-connect-solr-sink

Hope you are trying to push JSON data from Kafka to Solr and your solr schema is defined correctly. 
Without knowing the data being pushed and solr schema details and stack trace. It would be impossible to know what went wrong.

**Comment by ramyogi** [comment]
Thanks a lot. I like your code and it is a good reference. I completed integrating all with your connector. I am extending further for error scenario to place in Dead Lead queue(topic) something to replay.
