### ISSUE TITLE
Better documentation for config solr.url

### ISSUE THREAD

**Issue by Zaijo** [bkatwal/kafka-solr-sink-connector#7]
Hello, thanks for the solr sink!

I just spent about an hour debugging why solr sink would not update my solr core and I ended up with this idea about wiki.

![Image 22-09-2020 at 15 23](https://user-images.githubusercontent.com/1964908/93888018-bc98d900-fce7-11ea-97f0-ef3b00d55ac6.jpg)

Can you, please, update the wiki? I can't create a PR to the wiki. Otherwise I would just do it.
Thanks.

**Comment by bkatwal** [comment]
wiki is updated
